"""add offices table and handling_office column

Revision ID: e04cc00a16da
Revises: 6430a5cd51fb
Create Date: 2026-07-08 10:11:15.210684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04cc00a16da'
down_revision: Union[str, Sequence[str], None] = '6430a5cd51fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('office_code', sa.String(length=10), nullable=False),
    sa.Column('office_name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('office_code')
    )
    op.add_column('bookings', sa.Column('handling_office', sa.String(length=10), nullable=True))
    op.create_foreign_key(
        'fk_bookings_handling_office', 'bookings', 'offices', ['handling_office'], ['office_code']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bookings_handling_office', 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'handling_office')
    op.drop_table('offices')
    # ### end Alembic commands ###
